<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Tidy questionnaire data: demo</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="tidy_questionnaire_data_demo_files/libs/clipboard/clipboard.min.js"></script>
<script src="tidy_questionnaire_data_demo_files/libs/quarto-html/quarto.js"></script>
<script src="tidy_questionnaire_data_demo_files/libs/quarto-html/popper.min.js"></script>
<script src="tidy_questionnaire_data_demo_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="tidy_questionnaire_data_demo_files/libs/quarto-html/anchor.min.js"></script>
<link href="tidy_questionnaire_data_demo_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="tidy_questionnaire_data_demo_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="tidy_questionnaire_data_demo_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="tidy_questionnaire_data_demo_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="tidy_questionnaire_data_demo_files/libs/bootstrap/bootstrap-13790fa039be7cba96834befe0161d9e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Tidy questionnaire data: demo</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="about" class="level2">
<h2 class="anchored" data-anchor-id="about">About</h2>
<p>The goal of this notebook is to compare various data analysis programming approaches to scoring questionnaire data–which is perhaps the most common operation to perform on questionnaire data.</p>
<p>One common approach is to have the data organized into a one-agent-per-row format so that responses to various questions are encoded in separate columns and by doing operations on those columns, new score columns can be computed.</p>
<p>When the data is organized into a one-response-per-row format (which we call the tidy questionnaire format), then several strategies are possible and we will explore maybe some of them.</p>
</section>
<section id="sample-dataset" class="level2">
<h2 class="anchored" data-anchor-id="sample-dataset">Sample dataset</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>bfi2 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/x_bfi2.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>psqi <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/psqi.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we will use a real, albeit small data set, as our goal is only to explore coding strategies that are nevertheless meant to apply to real use cases. This dataset contains data from 8 participants who completed at least one of two standard questionnaires, either once or twice. For simplicity, this dataset is offered as two distinct tabular csv files, one per questionnaire.</p>
<p>The first questionnaire in this dataset is a slightly modified version of the bfi-2 personality test which contains 60 questions. We picked this questionnaire for this example because it is well-known and widely used, contains many items and can be used to compute a large number of scores and subscores (called “domain scales” and “fact scales”). This dataset contains data for only three participants: two of these completed the questionnaire twice, and of them completed it only once.</p>
<p>The second questionnaire in this dataset is the “Pittsburgh Sleep Quality Index (PSQI)”. We chose this questionnaire because it uses a wide range of responses types (e.g., time of day, number of minutes, hours per night, ordered categories representing a frequency, open text responses, ratings of quality) and uses more complex scoring rules–this questionnaire may therefore pose additional challenges for data organization and analysis. This dataset contains data from 5 participants who all completed that questionnaire twice. Furthermore, one of these participants (agent_id “030”) is also included in the bfi-2 data.</p>
<p>For each question we recorded what response option participants chose, how long it took them to select that option once the question was displayed (each question was displayed one by one on the screen), and how long it took them to validate their response by clicking on the “Next” button (participants could change their responses, while a given question was displayed, but once they clicked “Next”, they were presented with the next question and could not navigate back to earlier questions.) These are just a subset of information that could be collected per response, which is nevertheless more than what seems to be typically collected in questionnaire data.</p>
</section>
<section id="data-formats-tidylong-vs-untidywide" class="level2">
<h2 class="anchored" data-anchor-id="data-formats-tidylong-vs-untidywide">Data formats: tidy/long vs untidy/wide</h2>
<p>We stored the two data tables in the tidy questionnaire data format and will now create a version of these two data files that follows the “one-person-per-row” (aka “wide”) format. Furthermore, we will combine both pairs of files to form a combined tidy and a combined wide table respectively. This is to illustrate in particular how data from multiple questionnaires may be combined and how sparsity in each questionnaire data affects the size of the resulting combined tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># step 1: create wide data versions of the two tables</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bfi2_wide <span class="ot">&lt;-</span> bfi2 <span class="sc">|&gt;</span> <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> <span class="fu">c</span>(agent_id, instrument_id), </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">names_from =</span> <span class="fu">c</span>(stimulus_id, iteration), </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">names_glue =</span> <span class="st">"{stimulus_id}_{.value}_i{iteration}"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">values_from =</span> <span class="fu">c</span>(trial_index,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                                           stimulus_type,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                                           stimulus_description, </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                                           response_option_index, </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                                           response_description, </span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                                           response_numeric, </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                                           response_time, </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>                                           response_validation_time))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>psqi_wide <span class="ot">&lt;-</span> psqi <span class="sc">|&gt;</span> <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> <span class="fu">c</span>(agent_id, instrument_id), </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>                           <span class="at">names_from =</span> <span class="fu">c</span>(stimulus_id, iteration), </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>                           <span class="at">names_glue =</span> <span class="st">"{stimulus_id}_{.value}_i{iteration}"</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                          <span class="at">values_from =</span> <span class="fu">c</span>(trial_index,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>                                           stimulus_type,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>                                           stimulus_description, </span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>                                           response_option_index, </span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>                                           response_description, </span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>                                           response_numeric, </span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>                                           response_time, </span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>                                           response_validation_time))</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="co"># step 2: create a table that combines data from the two questionnaires</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>D_tidy <span class="ot">&lt;-</span> <span class="fu">rbind</span>(bfi2, psqi)</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>D_wide <span class="ot">&lt;-</span> <span class="fu">full_join</span>(bfi2_wide, psqi_wide, <span class="at">by =</span> <span class="st">"agent_id"</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co"># step 3: save the generated tables as csv files</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(bfi2_wide, <span class="at">file =</span> <span class="st">'data/x_bfi2_wide.csv'</span>)</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(psqi_wide, <span class="at">file =</span> <span class="st">'data/psqi_wide.csv'</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(D_tidy, <span class="at">file =</span> <span class="st">'data/D_tidy.csv'</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(D_wide, <span class="at">file =</span> <span class="st">'data/D_wide.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Dimensions and NA counts for each dataset, separately and combined, under the tidy and the wide tabular formats.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">dataset</th>
<th style="text-align: right;">rows</th>
<th style="text-align: right;">columns</th>
<th style="text-align: right;">rows x cols</th>
<th style="text-align: right;">NAs</th>
<th style="text-align: left;">csv size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">bfi2</td>
<td style="text-align: right;">305</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">3660</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">31.5 KB</td>
</tr>
<tr class="even">
<td style="text-align: left;">psqi</td>
<td style="text-align: right;">190</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">2280</td>
<td style="text-align: right;">100</td>
<td style="text-align: left;">27.5 KB</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D_tidy (combined)</td>
<td style="text-align: right;">495</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">5940</td>
<td style="text-align: right;">115</td>
<td style="text-align: left;">66.6 KB</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">bfi2_wide</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">978</td>
<td style="text-align: right;">2934</td>
<td style="text-align: right;">503</td>
<td style="text-align: left;">59.6 KB</td>
</tr>
<tr class="even">
<td style="text-align: left;">psqi_wide</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">306</td>
<td style="text-align: right;">1530</td>
<td style="text-align: right;">100</td>
<td style="text-align: left;">36.2 KB</td>
</tr>
<tr class="odd">
<td style="text-align: left;">D_wide (combined)</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">1283</td>
<td style="text-align: right;">8981</td>
<td style="text-align: right;">5121</td>
<td style="text-align: left;">109.1 KB</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are several important points to note in the table above. The tidy data tables all have the same small number of columns; their number of rows will vary depending on the amount of data collected. Conversely, their wide-formatted counterparts have a number of rows and columns that both depend on the specific dataset and study design (e.g., more repetitions of the same questions would lead to more columns). Thus the shape of the tables when they are wide is less predictable. Furthermore, because columns represent the attributes of an observation, the wide format is much more difficult to process. For example, there are 978 columns in the wide version of the bfi2 data but only 12 in its tidy version. When looking at the number of missing values it is clear to see that in some cases (when data is sparse), the number of missing values increases substantially when transforming the data from tidy to wide (for bfi2, that number increased from 15 to 503). Another important observation is that when combining tidy questionnaire tables, the resulting table is easily predictable: the numbers of rows and the number of NAs are simply added, while the number (and meaning) of the columns remain the same. In contrast, when combining wide data tables, the resulting table is unpredictable without knowledge about the content of the data. Note also the large increase in NAs for this combined table (5121) compared to the combined tidy data (115).</p>
<p>We also wanted to assess whether these data formats affect the size of the data. One simple but somewhat naive way of assessing size is to count the number of cells in each table. While this may in principle serve as a proxy, it is not that straightforward because the data in each cell may require more or less memory space depending for instance on how it is encoded (e.g., a boolean vs a string). The strategy we chose here was to save the various data tables as csv files and assess the size of those files. As can be seen in the table, the wide formats in our example are systematically larger than their tidy counterparts.</p>
</section>
<section id="scoring-questionnaires" class="level2">
<h2 class="anchored" data-anchor-id="scoring-questionnaires">Scoring questionnaires</h2>
<p>The next step will be to score each of the questionnaires, using the tidy and wide data formats and compare their advantages and disadvantages. In addition to computing those scores we will also compute the median response time to answer the corresponding questions. While this is not classically done, the idea of including it here is to assess how computing additional metrics on more than one response attribute would affect the complexity of the code.</p>
<section id="bfi-2" class="level3">
<h3 class="anchored" data-anchor-id="bfi-2">BFI-2</h3>
<section id="the-wide-data-format" class="level4">
<h4 class="anchored" data-anchor-id="the-wide-data-format">The wide data format</h4>
<p>We’ll start with the wide data format as this is the most common and the “approach” to scoring such data appears at least conceptually the most straightforward: because the data is already organized in an one-row-per-person format, scoring a questionnaire simply implies doing specific operations on a subset of the columns of that table.</p>
<p>Let’s start with a simple example: computing the <em>anxiety</em> score from the bfi2 data. According to the <a href="https://www.colby.edu/academics/departments-and-programs/psychology/research-opportunities/personality-lab/the-bfi-2/">documentation</a>, this requires using the responses from the items Anxiety: 4R, 19, 34, 49R (where R indicates items that need to be reverse coded).</p>
<p>So our first challenge is to figure out how to find the responses to those times in our dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># custom function to convert response option index into the response score as defined in documentation</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>compute_agreement_rate_vector <span class="ot">&lt;-</span> <span class="cf">function</span>(x, <span class="at">level_count =</span> <span class="dv">7</span>, <span class="at">reverse =</span> <span class="cn">FALSE</span>){</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  rate <span class="ot">&lt;-</span> (x<span class="dv">-1</span>)<span class="sc">/</span>(level_count<span class="dv">-1</span>)  </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (reverse){</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    rate <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>rate</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  rate</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># custom function to compute the anxiety score</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>compute_anxiety_score <span class="ot">&lt;-</span> <span class="cf">function</span>(df, iteration){</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># - Anxiety: 4R, 19, 34, 49R</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  iteration_text <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'_i'</span>, iteration)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a> (<span class="fu">compute_agreement_rate_vector</span>(df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_4_response_option_index'</span>, iteration_text)]], <span class="at">reverse =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">compute_agreement_rate_vector</span>(df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_19_response_option_index'</span>, iteration_text)]], <span class="at">reverse =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">compute_agreement_rate_vector</span>(df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_34_response_option_index'</span>, iteration_text)]], <span class="at">reverse =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">compute_agreement_rate_vector</span>(df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_49_response_option_index'</span>, iteration_text)]], <span class="at">reverse =</span> <span class="cn">TRUE</span>)) <span class="sc">/</span> <span class="dv">4</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="co"># computing the anxiety score and adding as a new column to the data</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>D_wide<span class="sc">$</span>anxiety_score_i1 <span class="ot">&lt;-</span> <span class="fu">compute_anxiety_score</span>(D_wide, <span class="at">iteration =</span> <span class="dv">1</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>D_wide<span class="sc">$</span>anxiety_score_i2 <span class="ot">&lt;-</span> <span class="fu">compute_anxiety_score</span>(D_wide, <span class="at">iteration =</span> <span class="dv">2</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="co"># we can do something similar to compute the average response times</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>compute_anxiety_response_times <span class="ot">&lt;-</span> <span class="cf">function</span>(df, iteration){</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  iteration_text <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">'_i'</span>, iteration)</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>  (df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_4_response_time'</span>, iteration_text)]] <span class="sc">+</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>  df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_19_response_time'</span>, iteration_text)]] <span class="sc">+</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_34_response_time'</span>, iteration_text)]] <span class="sc">+</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  df[[<span class="fu">paste0</span>(<span class="st">'bfi-2_q_49_response_time'</span>, iteration_text)]]) <span class="sc">/</span> <span class="dv">4</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>D_wide<span class="sc">$</span>anxiety_response_times_i1 <span class="ot">&lt;-</span> <span class="fu">compute_anxiety_response_times</span>(D_wide, <span class="at">iteration =</span> <span class="dv">1</span>)</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>D_wide<span class="sc">$</span>anxiety_response_times_i2 <span class="ot">&lt;-</span> <span class="fu">compute_anxiety_response_times</span>(D_wide, <span class="at">iteration =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>D_wide[<span class="fu">c</span>(<span class="st">'agent_id'</span>, <span class="st">'anxiety_score_i1'</span>, <span class="st">'anxiety_score_i2'</span>, <span class="st">'anxiety_response_times_i1'</span>, <span class="st">'anxiety_response_times_i2'</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 5
  agent_id anxiety_score_i1 anxiety_score_i2 anxiety_response_times_i1
  &lt;chr&gt;               &lt;dbl&gt;            &lt;dbl&gt;                     &lt;dbl&gt;
1 002                 0.542            0.708                      1.95
2 019                 0.458            0.625                      2.48
3 030                 0.625           NA                          2.28
4 008                NA               NA                         NA   
5 012                NA               NA                         NA   
6 026                NA               NA                         NA   
7 031                NA               NA                         NA   
# ℹ 1 more variable: anxiety_response_times_i2 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>There are several points we want to highlight about the code above. Firstly, this type of code tends to be quite verbose. We wrote functions here to aim to make that code compact; in practice it is rather common to not see any such functions but instead see long assignment statements.</p>
<p>Secondly, the code above is strongly tied, not only to information about the questionnaire (e.g., which items to pick)–which is unavoidable–, it is also strongly tied to the specific way in which the column names have been arbitrarily constructed. If for some reason we change how column names are constructed, we could have to replace all of the code above. Furthermore, if the study had not involved repetitions, the naming would have been different and thus we would have again to change the code.</p>
<p>Third, as in our example there are (up to) 2 repetitions of this questionnaire, we have to manually run the scoring code on each value of those iterations. Again, if there were a different number of iterations or different intentions to group data (e.g., completing surveys in morning vs evening), we would again have to change the code above.</p>
<p>Finally, when computing multiple aggregates on a particular response (in our example, how long they took to respond to those questions), we can see that it requires pretty much writing an independent chunk of code (the code for the anxiety response time and the code for anxiety scores are run independently from each other). This means that there are redundancies and the potential for mistakes. For example, the selection of items is the same in both cases (i.e., 4R, 19, 34, 49R), but this selection is specified in two different locations (both as part of the column names to be selected). As these are entered manually, and because for a given study there could potentially be a large number of such duplicated lists (e.g., there are 20 scores that one can compute out of this bfi2 questionnaire) which makes it hard to not make mistakes and to check that no mistakes were made. The above code takes about 25 lines to compute two metrics for one dimension; if we extrapolate, scoring the bfi2 questionnaire in this way would require 500 lines of code.</p>
<blockquote class="blockquote">
<p>The names of the aggregated values need to be specified by the data analyst. For example, here we chose “anxiety_score_i1”. This is again an arbitrary choice (we could have picked instead “score_bfi_anx_1”, “anxiety_r1_bfi2”, or something else). This custom naming of the outputs requires extra work, is specific to the dataset (if there were more repetitions, we would need additional assignment statements); it will also cause the subsequent code to be tailor made to those specific column names.</p>
</blockquote>
<p>It is of course possible to develop more custom code (i.e., more functions) to make the data analysis code more compact, less redundant and less error prone. But that code would require extra work, it would likely be highly specific to the way the column names were constructed for this particular dataset, and in practice, this does not seem to be what data analysts do.</p>
</section>
<section id="the-tidy-data-format" class="level4">
<h4 class="anchored" data-anchor-id="the-tidy-data-format">The tidy data format</h4>
<p>We will now do the same type of analysis starting with the tidy data format.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>score_bfi2_anxiety <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    df <span class="sc">|&gt;</span> </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># "select" the relevant items for this scale</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(stimulus_id <span class="sc">%in%</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">19</span>, <span class="dv">34</span>, <span class="dv">49</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># recode responses into 0-1 </span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">response_score =</span> <span class="fu">ifelse</span>(stimulus_id <span class="sc">%in%</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">49</span>)), </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">compute_agreement_rate_vector</span>(response_option_index, <span class="at">reverse =</span> <span class="cn">TRUE</span>), <span class="co"># reverse score for selected items </span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                                   <span class="fu">compute_agreement_rate_vector</span>(response_option_index, <span class="at">reverse =</span> <span class="cn">FALSE</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># compute score for this scale</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">dimension =</span> <span class="st">"bfi2_extraversion"</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">score =</span> <span class="fu">mean</span>(response_score), </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">response_time_mean =</span> <span class="fu">mean</span>(response_time),</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the scores for our dataset</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>bfi2_anxiety <span class="ot">&lt;-</span> D_tidy <span class="sc">|&gt;</span> </span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agent_id, iteration) <span class="sc">|&gt;</span> </span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">score_bfi2_anxiety</span>()</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(bfi2_anxiety)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">agent_id</th>
<th style="text-align: right;">iteration</th>
<th style="text-align: left;">dimension</th>
<th style="text-align: right;">score</th>
<th style="text-align: right;">response_time_mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">002</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.5416667</td>
<td style="text-align: right;">1.9545</td>
</tr>
<tr class="even">
<td style="text-align: left;">002</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.7083333</td>
<td style="text-align: right;">2.0165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">019</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.4583333</td>
<td style="text-align: right;">2.4805</td>
</tr>
<tr class="even">
<td style="text-align: left;">019</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.6250000</td>
<td style="text-align: right;">14.0690</td>
</tr>
<tr class="odd">
<td style="text-align: left;">030</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.6250000</td>
<td style="text-align: right;">2.2760</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are several points worth noting about the code above. Firstly, the code in <code>score_bfi2_anxiety()</code> only contains information about the IDs of the items that need to be used and how they are to be used. It does not contain any information related to the specifics of the study or data analysis intention. For instance, there is no notion of “repetition” in this code. Second, the selection of relevant items is done only once with the filter statement; this makes the code more compact and less error prone. Thirdly, the way that aggregates are computed on the data–which is done via the <code>summarize()</code>–makes it very easy to add additional metrics. For instance, if one wanted to also compute the minimum, maximum of and standard deviation of the response times, it would only require one additional statement per metric within the summarise function (e.g., <code>response_time_min = min(response_time)</code>; this is in stark contrast with how we analyzed the wide data.</p>
<p>Forth, if we look at how those functions are being applied to the data, we can see that by using the <code>group_by()</code> function (which is part of the dplyr package, included in the tidyverse) we can apply the scoring functions for any type of subset of our data. Here we specify that we want to have separate scoring for each agent and for each iteration. We don’t need to know or specify in advance how many iterations are in the dataset. The number of iterations does not impact the amount of code one needs to write. This code is also easy to update in the future; if there was a “time_of_day” column, that column could be used to compute different scores for whatever levels that variable has by simply changing the contents of that group_by() function. Importantly, this coding approach cleanly separates the scoring function which is tied only to the questionnaire used from the specific study design and data analysis strategies (which in our example is embedded in the group_by() function call).</p>
<p>It is also important to note that the output of the scoring “anxiety” following this approach is again a tidy table where no extra effort was required to name things. The shape of this table will depend on the specific analysis that was computed (e.g., if there are more iterations, there will be more rows), but the columns of that table will reflect the various metrics computed in the summary call.</p>
<p>Of course at some point one may want to display the table as a one-row-per-person table; this can be done quite easily.</p>
</section>
<section id="scoring-the-bfi2-questionnaire-as-a-whole" class="level4">
<h4 class="anchored" data-anchor-id="scoring-the-bfi2-questionnaire-as-a-whole">Scoring the bfi2 questionnaire as a whole</h4>
<p>As stated earlier we won’t use the strategy we employed for the wide data to score all of the dimensions as this would take us quite some time to do and would not be very interesting. But doing this exercise would certainly allow the reader to experience how painful that could be.</p>
<p>Here we will only use the tidy data as a starting point. We will abstract the code above a bit more to show how compact questionnaire data analysis may be.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># function to "recode" response values</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>compute_agreement_rate <span class="ot">&lt;-</span> <span class="cf">function</span>(df, <span class="at">col =</span> <span class="st">"response_option_index"</span>, <span class="at">level_count =</span> <span class="dv">7</span>, <span class="at">reverse =</span> <span class="cn">FALSE</span>){</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  rate <span class="ot">&lt;-</span> (df[[col]] <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">/</span> (level_count <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (reverse){</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    rate <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> rate</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  rate</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="co"># function takes as input a data frame (df) and a list containing the parameters of a specific scale and outputs the resulting scores and response times</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># recode and aggregate</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>score_questionnaire <span class="ot">&lt;-</span> <span class="cf">function</span>(df, scoring_params){</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># if reverse_ids is not defined, copy stimulus_ids</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">all</span>(<span class="fu">is.na</span>(scoring_params<span class="sc">$</span>reverse_ids))){</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    scoring_params<span class="sc">$</span>reverse_ids <span class="ot">&lt;-</span> <span class="st">"__none__"</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">|&gt;</span> </span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(stimulus_id <span class="sc">%in%</span> scoring_params<span class="sc">$</span>stimulus_ids) <span class="sc">|&gt;</span> </span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">response_score =</span> <span class="fu">ifelse</span>(stimulus_id <span class="sc">%in%</span> scoring_params<span class="sc">$</span>reverse_ids, </span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>                                   scoring_params<span class="sc">$</span><span class="fu">recode_func</span>(<span class="fu">pick</span>(<span class="fu">everything</span>()), <span class="at">reverse =</span> <span class="cn">TRUE</span>), </span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>                                   scoring_params<span class="sc">$</span><span class="fu">recode_func</span>(<span class="fu">pick</span>(<span class="fu">everything</span>()), <span class="at">reverse =</span> <span class="cn">FALSE</span>))) <span class="sc">|&gt;</span> </span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">dimension =</span> scoring_params<span class="sc">$</span>dimension,</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>              <span class="at">score =</span> <span class="fu">mean</span>(response_score, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>              <span class="at">response_time =</span> <span class="fu">mean</span>(response_time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>              <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>              <span class="at">na_n =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(response_time)),</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>              ) </span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code above is quite generic and applies to the common case where response option indices are converted to numbers using a particular set of rules and then aggregated. Because this code is generic and could apply to a wide range of questionnaires, it could be part of a package and reused broadly, preventing the need to write custom code.</p>
<p>We wrote the code in a way that the <code>score_questionnaire()</code> takes as input the questionnaire data and a list of parameters that specify how to score a particular dimension. This type of code that separates the specifics of a score (tied to a particular instrument) from the mechanics of computing the score is preferable over hard coding the specifics in the analysis code directly (as we did earlier) as it makes it easier to review if the specification is correct or not.</p>
<p>To compute a specific score, we will then need to do the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can now encode the scoring rules for the questionnaire in a compact way:</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>bfi2_extraversion <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_extraversion"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">11</span>, <span class="dv">16</span>, <span class="dv">21</span>, <span class="dv">26</span>, <span class="dv">31</span>, <span class="dv">36</span>, <span class="dv">41</span>, <span class="dv">46</span>, <span class="dv">51</span>, <span class="dv">56</span>)),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">16</span>, <span class="dv">26</span>, <span class="dv">31</span>, <span class="dv">36</span>, <span class="dv">51</span>))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># and use the generic code to compute the results for that dimension:</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>D_tidy <span class="sc">|&gt;</span> </span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agent_id, iteration) <span class="sc">|&gt;</span> </span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">score_questionnaire</span>(bfi2_extraversion) <span class="sc">|&gt;</span> </span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 26%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 4%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">agent_id</th>
<th style="text-align: right;">iteration</th>
<th style="text-align: left;">dimension</th>
<th style="text-align: right;">score</th>
<th style="text-align: right;">response_time</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">na_n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">002</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.6111111</td>
<td style="text-align: right;">11.823333</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">002</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.5972222</td>
<td style="text-align: right;">2.045917</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">019</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.7500000</td>
<td style="text-align: right;">2.151667</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">019</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.6805556</td>
<td style="text-align: right;">13.529833</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">030</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">bfi2_extraversion</td>
<td style="text-align: right;">0.6388889</td>
<td style="text-align: right;">1.762917</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>To compute all of the 20 scores from the bfi2 questionnaires, we first need to specify the parameters for each score. This can be done all in one, easy to review, place:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Storing all the scoring rules for the bfi-2 questionnaire in lists:</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Extraversion: 1, 6, 11R, 16R, 21, 26R, 31R, 36R, 41, 46, 51R, 56</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>bfi2_extraversion <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_extraversion"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">6</span>, <span class="dv">11</span>, <span class="dv">16</span>, <span class="dv">21</span>, <span class="dv">26</span>, <span class="dv">31</span>, <span class="dv">36</span>, <span class="dv">41</span>, <span class="dv">46</span>, <span class="dv">51</span>, <span class="dv">56</span>)),</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">16</span>, <span class="dv">26</span>, <span class="dv">31</span>, <span class="dv">36</span>, <span class="dv">51</span>))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Agreeableness: 2, 7, 12R, 17R, 22R, 27, 32, 37R, 42R, 47R, 52, 57</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>bfi2_agreeableness <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_agreeableness"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">12</span>, <span class="dv">17</span>, <span class="dv">22</span>, <span class="dv">27</span>, <span class="dv">32</span>, <span class="dv">37</span>, <span class="dv">42</span>, <span class="dv">47</span>, <span class="dv">52</span>, <span class="dv">57</span>)),</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">17</span>, <span class="dv">22</span>, <span class="dv">37</span>, <span class="dv">42</span>, <span class="dv">47</span>))</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="do">## Conscientiousness: 3R, 8R, 13, 18, 23R, 28R, 33, 38, 43, 48R, 53, 58R</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>bfi2_conscientiousness <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_conscientiousness"</span>,</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">8</span>, <span class="dv">13</span>, <span class="dv">18</span>, <span class="dv">23</span>, <span class="dv">28</span>, <span class="dv">33</span>, <span class="dv">38</span>, <span class="dv">43</span>, <span class="dv">48</span>, <span class="dv">53</span>, <span class="dv">58</span>)),</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">8</span>, <span class="dv">23</span>, <span class="dv">28</span>, <span class="dv">48</span>, <span class="dv">58</span>))</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="do">## Negative Emotionality: 4R, 9R, 14, 19, 24R, 29R, 34, 39, 44R, 49R, 54, 59</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>bfi2_negative <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_negative"</span>,</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">14</span>, <span class="dv">19</span>, <span class="dv">24</span>, <span class="dv">29</span>, <span class="dv">34</span>, <span class="dv">39</span>, <span class="dv">44</span>, <span class="dv">49</span>, <span class="dv">54</span>, <span class="dv">59</span>)),</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">9</span>, <span class="dv">24</span>, <span class="dv">29</span>, <span class="dv">44</span>, <span class="dv">49</span>))</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="do">## Open-Mindedness: 5R, 10, 15, 20, 25R, 30R, 35, 40, 45R, 50R, 55R, 60</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>bfi2_open <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_open"</span>,</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">35</span>, <span class="dv">40</span>, <span class="dv">45</span>, <span class="dv">50</span>, <span class="dv">55</span>, <span class="dv">60</span>)),</span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">25</span>, <span class="dv">30</span>, <span class="dv">45</span>, <span class="dv">50</span>, <span class="dv">55</span>))</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a><span class="do">## Sociability: 1, 16R, 31R, 46</span></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>bfi2_sociability <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_sociability"</span>,</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">16</span>, <span class="dv">31</span>, <span class="dv">46</span>)),</span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">16</span>, <span class="dv">31</span>))</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a><span class="do">## Assertiveness: 6, 21, 36R, 51R</span></span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>bfi2_assertiveness <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_assertiveness"</span>,</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">6</span>, <span class="dv">21</span>, <span class="dv">36</span>, <span class="dv">51</span>)),</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">36</span>, <span class="dv">51</span>))</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a><span class="do">## Energy Level: 11R, 26R, 41, 56</span></span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a>bfi2_energy <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_energy"</span>,</span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">26</span>, <span class="dv">41</span>, <span class="dv">56</span>)),</span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">11</span>, <span class="dv">26</span>))</span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a><span class="do">## Compassion: 2, 17R, 32, 47R</span></span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>bfi2_compassion <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_compassion"</span>,</span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">17</span>, <span class="dv">32</span>, <span class="dv">47</span>)),</span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">17</span>, <span class="dv">47</span>))</span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a><span class="do">## Respectfulness: 7, 22R, 37R, 52</span></span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a>bfi2_respectfulness <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-77"><a href="#cb10-77" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_respectfulness"</span>,</span>
<span id="cb10-78"><a href="#cb10-78" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-79"><a href="#cb10-79" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">22</span>, <span class="dv">37</span>, <span class="dv">52</span>)),</span>
<span id="cb10-80"><a href="#cb10-80" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">22</span>, <span class="dv">37</span>))</span>
<span id="cb10-81"><a href="#cb10-81" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-82"><a href="#cb10-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-83"><a href="#cb10-83" aria-hidden="true" tabindex="-1"></a><span class="do">## Trust: 12R, 27, 42R, 57</span></span>
<span id="cb10-84"><a href="#cb10-84" aria-hidden="true" tabindex="-1"></a>bfi2_trust <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-85"><a href="#cb10-85" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_trust"</span>,</span>
<span id="cb10-86"><a href="#cb10-86" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-87"><a href="#cb10-87" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">27</span>, <span class="dv">42</span>, <span class="dv">57</span>)),</span>
<span id="cb10-88"><a href="#cb10-88" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">27</span>, <span class="dv">57</span>))</span>
<span id="cb10-89"><a href="#cb10-89" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-90"><a href="#cb10-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-91"><a href="#cb10-91" aria-hidden="true" tabindex="-1"></a><span class="do">## Organization: 3R, 18, 33, 48R</span></span>
<span id="cb10-92"><a href="#cb10-92" aria-hidden="true" tabindex="-1"></a>bfi2_organization <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-93"><a href="#cb10-93" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_organization"</span>,</span>
<span id="cb10-94"><a href="#cb10-94" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-95"><a href="#cb10-95" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">18</span>, <span class="dv">33</span>, <span class="dv">48</span>)),</span>
<span id="cb10-96"><a href="#cb10-96" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">48</span>))</span>
<span id="cb10-97"><a href="#cb10-97" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-98"><a href="#cb10-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-99"><a href="#cb10-99" aria-hidden="true" tabindex="-1"></a><span class="do">## Productiveness: 8R, 23R, 38, 53</span></span>
<span id="cb10-100"><a href="#cb10-100" aria-hidden="true" tabindex="-1"></a>bfi2_productiveness <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-101"><a href="#cb10-101" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_productiveness"</span>,</span>
<span id="cb10-102"><a href="#cb10-102" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-103"><a href="#cb10-103" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">23</span>, <span class="dv">38</span>, <span class="dv">53</span>)),</span>
<span id="cb10-104"><a href="#cb10-104" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">8</span>, <span class="dv">23</span>))</span>
<span id="cb10-105"><a href="#cb10-105" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-106"><a href="#cb10-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-107"><a href="#cb10-107" aria-hidden="true" tabindex="-1"></a><span class="do">## Responsibility: 13, 28R, 43, 58R</span></span>
<span id="cb10-108"><a href="#cb10-108" aria-hidden="true" tabindex="-1"></a>bfi2_responsibility <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-109"><a href="#cb10-109" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_responsibility"</span>,</span>
<span id="cb10-110"><a href="#cb10-110" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-111"><a href="#cb10-111" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">13</span>, <span class="dv">28</span>, <span class="dv">43</span>, <span class="dv">58</span>)),</span>
<span id="cb10-112"><a href="#cb10-112" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">28</span>, <span class="dv">58</span>))</span>
<span id="cb10-113"><a href="#cb10-113" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-114"><a href="#cb10-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-115"><a href="#cb10-115" aria-hidden="true" tabindex="-1"></a><span class="do">## Anxiety: 4R, 19, 34, 49R</span></span>
<span id="cb10-116"><a href="#cb10-116" aria-hidden="true" tabindex="-1"></a>bfi2_anxiety <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-117"><a href="#cb10-117" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_anxiety"</span>,</span>
<span id="cb10-118"><a href="#cb10-118" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-119"><a href="#cb10-119" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">19</span>, <span class="dv">34</span>, <span class="dv">49</span>)),</span>
<span id="cb10-120"><a href="#cb10-120" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">49</span>))</span>
<span id="cb10-121"><a href="#cb10-121" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-122"><a href="#cb10-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-123"><a href="#cb10-123" aria-hidden="true" tabindex="-1"></a><span class="do">## Depression: 9R, 24R, 39, 54</span></span>
<span id="cb10-124"><a href="#cb10-124" aria-hidden="true" tabindex="-1"></a>bfi2_depression <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-125"><a href="#cb10-125" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_depression"</span>,</span>
<span id="cb10-126"><a href="#cb10-126" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-127"><a href="#cb10-127" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">24</span>, <span class="dv">39</span>, <span class="dv">54</span>)),</span>
<span id="cb10-128"><a href="#cb10-128" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">9</span>, <span class="dv">24</span>))</span>
<span id="cb10-129"><a href="#cb10-129" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-130"><a href="#cb10-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-131"><a href="#cb10-131" aria-hidden="true" tabindex="-1"></a><span class="do">## Emotional Volatility: 14, 29R, 44R, 59</span></span>
<span id="cb10-132"><a href="#cb10-132" aria-hidden="true" tabindex="-1"></a>bfi2_volatility <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-133"><a href="#cb10-133" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_volatility"</span>,</span>
<span id="cb10-134"><a href="#cb10-134" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-135"><a href="#cb10-135" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">14</span>, <span class="dv">29</span>, <span class="dv">44</span>, <span class="dv">59</span>)),</span>
<span id="cb10-136"><a href="#cb10-136" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">29</span>, <span class="dv">44</span>))</span>
<span id="cb10-137"><a href="#cb10-137" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-138"><a href="#cb10-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-139"><a href="#cb10-139" aria-hidden="true" tabindex="-1"></a><span class="do">## Intellectual Curiosity: 10, 25R, 40, 55R</span></span>
<span id="cb10-140"><a href="#cb10-140" aria-hidden="true" tabindex="-1"></a>bfi2_curiosity <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-141"><a href="#cb10-141" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_curiosity"</span>,</span>
<span id="cb10-142"><a href="#cb10-142" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-143"><a href="#cb10-143" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">10</span>, <span class="dv">25</span>, <span class="dv">40</span>, <span class="dv">55</span>)),</span>
<span id="cb10-144"><a href="#cb10-144" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">25</span>, <span class="dv">55</span>))</span>
<span id="cb10-145"><a href="#cb10-145" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-146"><a href="#cb10-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-147"><a href="#cb10-147" aria-hidden="true" tabindex="-1"></a><span class="do">## Aesthetic Sensitivity: 5R, 20, 35, 50R</span></span>
<span id="cb10-148"><a href="#cb10-148" aria-hidden="true" tabindex="-1"></a>bfi2_aesthetic <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-149"><a href="#cb10-149" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_aesthetic"</span>,</span>
<span id="cb10-150"><a href="#cb10-150" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-151"><a href="#cb10-151" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">20</span>, <span class="dv">35</span>, <span class="dv">50</span>)),</span>
<span id="cb10-152"><a href="#cb10-152" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">50</span>))</span>
<span id="cb10-153"><a href="#cb10-153" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-154"><a href="#cb10-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-155"><a href="#cb10-155" aria-hidden="true" tabindex="-1"></a><span class="do">## Creative Imagination: 15, 30R, 45R, 60</span></span>
<span id="cb10-156"><a href="#cb10-156" aria-hidden="true" tabindex="-1"></a>bfi2_imagination <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb10-157"><a href="#cb10-157" aria-hidden="true" tabindex="-1"></a>  <span class="at">dimension =</span> <span class="st">"bfi2_imagination"</span>,</span>
<span id="cb10-158"><a href="#cb10-158" aria-hidden="true" tabindex="-1"></a>  <span class="at">recode_func =</span> compute_agreement_rate,</span>
<span id="cb10-159"><a href="#cb10-159" aria-hidden="true" tabindex="-1"></a>  <span class="at">stimulus_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>, <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">30</span>, <span class="dv">45</span>, <span class="dv">60</span>)),</span>
<span id="cb10-160"><a href="#cb10-160" aria-hidden="true" tabindex="-1"></a>  <span class="at">reverse_ids =</span> <span class="fu">paste0</span>(<span class="st">"bfi-2_q_"</span>,  <span class="fu">c</span>(<span class="dv">30</span>, <span class="dv">45</span>))</span>
<span id="cb10-161"><a href="#cb10-161" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that the above is a sort of documentation of how to score the bfi2 questionnaire; this content should be an integral part of the questionnaire (and questionnaire data collection system) itself rather than being manually entered as we did here.</p>
<p>Once we have defined the list of scores we want to compute on our data, we can create a list of those parameter lists:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## We can group all of those scale parameter lists into an instrument specific list</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>bfi2_params <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 5 domain scales:</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  bfi2_extraversion,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  bfi2_agreeableness,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>  bfi2_conscientiousness,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>  bfi2_negative,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  bfi2_open,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># 15 facets:</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  bfi2_sociability,</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  bfi2_assertiveness,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  bfi2_energy,</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  bfi2_compassion,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>  bfi2_respectfulness,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>  bfi2_trust,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>  bfi2_organization,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>  bfi2_productiveness, </span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  bfi2_responsibility,</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  bfi2_anxiety,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>  bfi2_depression,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>  bfi2_volatility,</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  bfi2_curiosity,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>  bfi2_aesthetic,</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>  bfi2_imagination)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The next step is then to execute the scoring code on each of them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we use purrr instead of for loops</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># we also first create a wrapper to simplify code</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(df, param_list){</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">|&gt;</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">group_by</span>(agent_id, iteration) <span class="sc">|&gt;</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">score_questionnaire</span>(param_list)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>bfi2_scores <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(bfi2_params, <span class="sc">~</span> <span class="fu">f</span>(D_tidy, .x))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Thus if we exclude the generic code and the specification of how to score the bfi2 questionnaire, the code to score the questionnaire only takes a handful of lines of code, which are the same irrespective of the number of scores to extract from the questionnaire or from the number of iterations that participants completed.</p>
<p>Some people might want at this stage to have a table showing for each person their score on the various dimensions of the questionnaire. We could simply use pivot_wider() here to create a one-person-per-row table. However, it is unlikely that we would want to display all of the data in bfi2_scores. As an example, we will only display the scores (i.e., ignoring response_time, n and na_n) and average the scores across repetitions when there are multiple.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>bfi2_scores_wide <span class="ot">&lt;-</span> bfi2_scores <span class="sc">|&gt;</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># averaging scores across repetitions for each dimension</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agent_id, dimension) <span class="sc">|&gt;</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">score =</span> <span class="fu">mean</span>(score, <span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># reshaping the table</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> agent_id, <span class="at">names_from =</span> dimension, <span class="at">values_from =</span> score)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(bfi2_scores_wide)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 4%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 4%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 4%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">agent_id</th>
<th style="text-align: right;">bfi2_aesthetic</th>
<th style="text-align: right;">bfi2_agreeableness</th>
<th style="text-align: right;">bfi2_anxiety</th>
<th style="text-align: right;">bfi2_assertiveness</th>
<th style="text-align: right;">bfi2_compassion</th>
<th style="text-align: right;">bfi2_conscientiousness</th>
<th style="text-align: right;">bfi2_curiosity</th>
<th style="text-align: right;">bfi2_depression</th>
<th style="text-align: right;">bfi2_energy</th>
<th style="text-align: right;">bfi2_extraversion</th>
<th style="text-align: right;">bfi2_imagination</th>
<th style="text-align: right;">bfi2_negative</th>
<th style="text-align: right;">bfi2_open</th>
<th style="text-align: right;">bfi2_organization</th>
<th style="text-align: right;">bfi2_productiveness</th>
<th style="text-align: right;">bfi2_respectfulness</th>
<th style="text-align: right;">bfi2_responsibility</th>
<th style="text-align: right;">bfi2_sociability</th>
<th style="text-align: right;">bfi2_trust</th>
<th style="text-align: right;">bfi2_volatility</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">002</td>
<td style="text-align: right;">0.5833333</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.6250000</td>
<td style="text-align: right;">0.4583333</td>
<td style="text-align: right;">0.7708333</td>
<td style="text-align: right;">0.4722222</td>
<td style="text-align: right;">0.7708333</td>
<td style="text-align: right;">0.7083333</td>
<td style="text-align: right;">0.7708333</td>
<td style="text-align: right;">0.6041667</td>
<td style="text-align: right;">0.7083333</td>
<td style="text-align: right;">0.6527778</td>
<td style="text-align: right;">0.6875000</td>
<td style="text-align: right;">0.4375000</td>
<td style="text-align: right;">0.4791667</td>
<td style="text-align: right;">0.7708333</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.5833333</td>
<td style="text-align: right;">0.5416667</td>
<td style="text-align: right;">0.625</td>
</tr>
<tr class="even">
<td style="text-align: left;">019</td>
<td style="text-align: right;">0.3958333</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.5416667</td>
<td style="text-align: right;">0.6458333</td>
<td style="text-align: right;">0.6041667</td>
<td style="text-align: right;">0.8541667</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">0.8125000</td>
<td style="text-align: right;">0.7152778</td>
<td style="text-align: right;">0.6041667</td>
<td style="text-align: right;">0.3194444</td>
<td style="text-align: right;">0.5555556</td>
<td style="text-align: right;">0.8750000</td>
<td style="text-align: right;">0.8541667</td>
<td style="text-align: right;">0.8125000</td>
<td style="text-align: right;">0.8333333</td>
<td style="text-align: right;">0.6875000</td>
<td style="text-align: right;">0.4166667</td>
<td style="text-align: right;">0.250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">030</td>
<td style="text-align: right;">0.0833333</td>
<td style="text-align: right;">0.4305556</td>
<td style="text-align: right;">0.6250000</td>
<td style="text-align: right;">0.7916667</td>
<td style="text-align: right;">0.3750000</td>
<td style="text-align: right;">0.7500000</td>
<td style="text-align: right;">0.7916667</td>
<td style="text-align: right;">0.3750000</td>
<td style="text-align: right;">0.6666667</td>
<td style="text-align: right;">0.6388889</td>
<td style="text-align: right;">0.7083333</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.5277778</td>
<td style="text-align: right;">0.8333333</td>
<td style="text-align: right;">0.7916667</td>
<td style="text-align: right;">0.5000000</td>
<td style="text-align: right;">0.6250000</td>
<td style="text-align: right;">0.4583333</td>
<td style="text-align: right;">0.5833333</td>
<td style="text-align: right;">0.500</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="psqi" class="level3">
<h3 class="anchored" data-anchor-id="psqi">PSQI</h3>
<p>The PSQI questionnaire is more challenging to score because it involves a larger variety of response formats and because the scoring procedure is a bit more involved.</p>
<p>Also for brevity we will only focus only on computing the score for “Component 2: Sleep latency” as it involves multiple steps.</p>
<section id="the-wide-data-format-1" class="level4">
<h4 class="anchored" data-anchor-id="the-wide-data-format-1">The wide data format</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># question 2: convert duration ranges into integer 0-3</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># question 5: convert choice into integer 0-3</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># sum previous two scores</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the sum into integer 0 -3</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># score question 2:</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>validate_psqi_question_2_input <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.numeric</span>(x)) {</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"Input must be numeric"</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">any</span>(x <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)){</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"Input must be larger than 0"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(x)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="co"># validate_psqi_question_2_input(c(1, 1, 2, NA))</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>score_psqi_question_2 <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">validate_psqi_question_2_input</span>(x)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>(<span class="fu">cut</span>(x, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">15</span>, <span class="dv">30</span>, <span class="dv">60</span>, <span class="dv">24</span><span class="sc">*</span><span class="dv">60</span>))) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a><span class="co"># score question 5:</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>validate_psqi_question_5_input <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>  q5_levels <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"not during the past month"</span>, <span class="st">"less than once a week"</span>, <span class="st">"once or twice a week"</span>, <span class="st">"three or more times a week"</span>)</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">is.factor</span>(x)) { <span class="co"># if x is encoded as a factor variable</span></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span> <span class="fu">all</span>(<span class="fu">levels</span>(x) <span class="sc">==</span> q5_levels)){</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>      <span class="fu">stop</span>(<span class="fu">paste0</span>(<span class="st">"Input does not have the required levels: </span><span class="sc">\n</span><span class="st">Input levels: "</span>, <span class="fu">levels</span>(x), <span class="st">"</span><span class="sc">\n</span><span class="st">Expected levels: "</span>, q5_levels))</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.character</span>(x)){</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"Input must be either factor or string"</span>)</span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>    <span class="co"># check inputs are </span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (element <span class="cf">in</span> x){</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="fu">is.na</span>(element)) <span class="cf">next</span></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="sc">!</span>element <span class="sc">%in%</span> q5_levels){</span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>        <span class="fu">stop</span>(<span class="fu">paste0</span>(<span class="st">"Input contains unexpected values: "</span>, element) )</span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(x)</span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a>score_psqi_question_5 <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">validate_psqi_question_5_input</span>(x)</span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>(</span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a>    <span class="fu">factor</span>(x, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"not during the past month"</span>, <span class="st">"less than once a week"</span>, <span class="st">"once or twice a week"</span>, <span class="st">"three or more times a week"</span>))</span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a><span class="co"># combine the subcomponent scores</span></span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a>score_sleep_latency_components <span class="ot">&lt;-</span> <span class="cf">function</span>(x,y){</span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.numeric</span>(</span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cut</span>(x <span class="sc">+</span> y, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>))</span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">-</span><span class="dv">1</span></span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a><span class="co"># wrapper to do all the previous steps in one function call</span></span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a>score_sleep_latency <span class="ot">&lt;-</span> <span class="cf">function</span>(q2,q5){</span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">score_psqi_question_2</span>(q2)</span>
<span id="cb15-75"><a href="#cb15-75" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">score_psqi_question_5</span>(q5)</span>
<span id="cb15-76"><a href="#cb15-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">score_sleep_latency_components</span>(x,y)</span>
<span id="cb15-77"><a href="#cb15-77" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The code above shows that one can write simple functions to process each question separately, a function to aggregate those results and a wrapper function to keep the data analysis code cleaner. It is important to note here that this code expects very specific input values: in the first case a number of minutes (i.e., a positive number between 0 and 1440), in the second, one out of 4 possible response categories. In the above code we show how the data analysis code can make sure that the input is as expected (as opposed to relying on the data being correctly formatted).</p>
<p>Having created those functions, we can now analyze our specific dataset:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use the above code to compute the psqi sleep latency score for each iteration and append to data</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>D_wide <span class="ot">&lt;-</span> D_wide <span class="sc">|&gt;</span> </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">psqi_latency_score_i1 =</span> <span class="fu">score_sleep_latency</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                      psqi_q_2_response_numeric_i1, </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">`</span><span class="at">frequency_trouble_sleep_because;psqi-past_q_6_response_description_i1</span><span class="st">`</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                                      ),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">psqi_latency_score_i2 =</span> <span class="fu">score_sleep_latency</span>(</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                                      psqi_q_2_response_numeric_i2, </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                                      <span class="st">`</span><span class="at">frequency_trouble_sleep_because;psqi-past_q_6_response_description_i2</span><span class="st">`</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                                      )</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>         ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The above code is rather compact thanks to the use of functions. However, as in with the bfi2_wide example, we end up having to write code that is specific to our study: we need to compute the scores separately for each iteration, which leads to duplicated code and the potential to make mistakes (forgetting to change the i1 to i2 when copy-pasting code).</p>
<p>The second observation: we add new columns to the main table; we are now mixing in the table things that are data (responses to questions) and things that we compute using that data (the psqi sleep latency score). We could of course save the resulting columns in a separate table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>D_wide <span class="sc">|&gt;</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(agent_id, psqi_latency_score_i1, psqi_latency_score_i2) <span class="sc">|&gt;</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">agent_id</th>
<th style="text-align: right;">psqi_latency_score_i1</th>
<th style="text-align: right;">psqi_latency_score_i2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">002</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">019</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">030</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">008</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">012</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">026</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">031</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="the-tidy-data-format-1" class="level4">
<h4 class="anchored" data-anchor-id="the-tidy-data-format-1">The tidy data format</h4>
<p>We could use an approach similar to what we did for BFI-2: define a list of parameters to compute a specific score and a generic function to run the analysis of data. This would work for calculating the subscores, but then a second step would be required to compute the aggregate score from those two subscores.</p>
<p>The alternative is to create a function that takes as input a data frame and returns the scores</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>score_sleep_latency_components_df <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">length</span>(x) <span class="sc">!=</span> <span class="dv">2</span>){</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stop</span>(<span class="st">"Data does not have the expected number of items"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">score_sleep_latency_components</span>(x[<span class="dv">1</span>], x[<span class="dv">2</span>])</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>score_psqi_latency <span class="ot">&lt;-</span> <span class="cf">function</span>(df){</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># because rowwise will override any existing groups, we need to save and restore them when needed</span></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>  group_vars <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">group_vars</span>(df)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>  df <span class="sc">|&gt;</span> </span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(stimulus_id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"psqi_q_2"</span>, <span class="st">"frequency_trouble_sleep_because;psqi-past_q_6"</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># process each question separately</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rowwise</span>() <span class="sc">|&gt;</span> </span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">score_tmp =</span> <span class="fu">ifelse</span>(stimulus_id<span class="sc">==</span><span class="st">"psqi_q_2"</span>, </span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">score_psqi_question_2</span>(response_numeric), </span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>                          <span class="cn">NA</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">score_tmp =</span> <span class="fu">ifelse</span>(stimulus_id<span class="sc">==</span><span class="st">"frequency_trouble_sleep_because;psqi-past_q_6"</span>,</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>                          <span class="fu">score_psqi_question_5</span>(response_description), </span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>                          score_tmp)) <span class="sc">|&gt;</span> </span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">|&gt;</span> </span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(group_vars))) <span class="sc">|&gt;</span> </span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># aggregate scores across all selected responses</span></span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">dimension =</span> <span class="st">"psqi_latency"</span>, </span>
<span id="cb18-33"><a href="#cb18-33" aria-hidden="true" tabindex="-1"></a>              <span class="at">score =</span> <span class="fu">score_sleep_latency_components_df</span>(score_tmp), </span>
<span id="cb18-34"><a href="#cb18-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">response_time =</span> <span class="fu">mean</span>(response_time, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb18-35"><a href="#cb18-35" aria-hidden="true" tabindex="-1"></a>              <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb18-36"><a href="#cb18-36" aria-hidden="true" tabindex="-1"></a>              <span class="at">na_n =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(response_time)),</span>
<span id="cb18-37"><a href="#cb18-37" aria-hidden="true" tabindex="-1"></a>              <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb18-38"><a href="#cb18-38" aria-hidden="true" tabindex="-1"></a>              ) </span>
<span id="cb18-39"><a href="#cb18-39" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb18-40"><a href="#cb18-40" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>D_tidy <span class="sc">|&gt;</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agent_id, iteration) <span class="sc">|&gt;</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">score_psqi_latency</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 7
   agent_id iteration dimension    score response_time     n  na_n
   &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt;         &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
 1 008              1 psqi_latency     2          5.73     2     0
 2 008              2 psqi_latency     3          7.95     2     0
 3 012              1 psqi_latency     2         13.2      2     0
 4 012              2 psqi_latency     1          5.34     2     0
 5 026              1 psqi_latency     3         10.5      2     0
 6 026              2 psqi_latency     2          5.38     2     0
 7 030              1 psqi_latency     1          3.69     2     0
 8 030              2 psqi_latency     1         10.0      2     0
 9 031              1 psqi_latency     1         23.5      2     0
10 031              2 psqi_latency     0         15.8      2     0</code></pre>
</div>
</div>
<p>The code in this case is quite a bit more complex; the main advantages are however that a) we can compute more metrics on the selected items without much effort (e.g., response_time) compared to the strategy we used on the wide data format and b) we can have studies that involve any number of iterations (or other types of grouping variables) and reuse the exact same code; in contrast, the code used on the wide data format is strongly tied to the specifics of the study, be it through the study parameters encoded in the column names or the number of steps required in the analysis.</p>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This notebook presents a more realistic, although still simplified, example of the analysis of questionnaire data using the wide and tidy data formats respectively. Overall, the tidy data format seems preferable for several reasons. However, we also note that in some cases handling the tidy data format may require code that is more complex than the wide data format.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>